# Generated by Django 4.2 on 2023-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('author', models.CharField(max_length=50)),
                ('metades', models.CharField(max_length=150)),
                ('image_title', models.ImageField(blank=True, null=True, upload_to='title-image/')),
                ('content', models.TextField()),
                ('images0', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images1', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images2', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images3', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images4', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images5', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images6', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images7', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images8', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('images9', models.ImageField(blank=True, null=True, upload_to='blog-image/')),
                ('file1', models.FileField(upload_to='blog-docs/')),
                ('file2', models.FileField(upload_to='blog-docs/')),
                ('file3', models.FileField(upload_to='blog-docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('categoty_image', models.ImageField(blank=True, null=True, upload_to='blog_cat/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['title'],
            },
        ),
    ]
