# Generated by Django 4.2 on 2023-05-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['continent'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('flag', models.ImageField(upload_to='flags')),
                ('language', models.CharField(max_length=50)),
                ('m_ethnic', models.CharField(max_length=500)),
                ('time_zone', models.CharField(max_length=50)),
                ('calling_code', models.CharField(max_length=10)),
                ('land_area', models.CharField(max_length=150)),
                ('climate', models.CharField(max_length=500)),
                ('goverment', models.CharField(max_length=500)),
                ('gdp', models.CharField(max_length=50)),
                ('date_of_independece', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_details.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['country'],
            },
        ),
    ]
