# Generated by Django 4.2 on 2023-05-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_details', '0002_alter_continent_continent_alter_country_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='date_of_independece',
            new_name='date_of_independence',
        ),
    ]
