# Generated by Django 4.2 on 2023-05-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_details', '0003_rename_date_of_independece_country_date_of_independence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags'),
        ),
    ]
